// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message ConcatenateVectorCalculatorOptions {
  extend CalculatorOptions {
    optional ConcatenateVectorCalculatorOptions ext = 259397839;
  }

  // If true, the calculator will only emit a packet at the given timestamp if
  // all input streams have a non-empty packet (AND operation on streams).
  optional bool only_emit_if_all_present = 1 [default = false];
}
