// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message PacketClonerCalculatorOptions {
  extend CalculatorOptions {
    optional PacketClonerCalculatorOptions ext = 258872085;
  }

  // When true, this calculator will drop received TICK packets if any input
  // stream hasn't received a packet yet.
  optional bool output_only_when_all_inputs_received = 1 [default = false];

  // Similar with above, but also transmit empty packet for all streams before
  // all inputs are received.
  optional bool output_packets_only_when_all_inputs_received = 2
      [default = false];
}
