// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message SequenceShiftCalculatorOptions {
  extend CalculatorOptions {
    optional SequenceShiftCalculatorOptions ext = 107633927;
  }
  optional int32 packet_offset = 1 [default = -1];

  // Emits empty packets before the first delayed packet is emitted. Takes
  // effect only when packet offset is set to positive.
  optional bool emit_empty_packets_before_first_packet = 2 [default = false];
}
