// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

// A Range {begin, end} specifies beginning ane ending indices to splice a
// vector. A vector v is spliced to have elements v[begin:(end-1)], i.e., with
// begin index inclusive and end index exclusive.
message Range {
  optional int32 begin = 1;
  optional int32 end = 2;
}

message SplitVectorCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional SplitVectorCalculatorOptions ext = 259438222;
  }

  repeated Range ranges = 1;

  // Specify if single element ranges should be outputted as std::vector<T> or
  // just element of type T. By default, if a range specifies only one element,
  // it is outputted as an std::vector<T>.
  optional bool element_only = 2 [default = false];

  // Combines output elements to one vector.
  optional bool combine_outputs = 3 [default = false];
}
