// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe.autoflip;

import "mediapipe/framework/calculator.proto";

message LocalizationToRegionCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional LocalizationToRegionCalculatorOptions ext = 284226721;
  }

  // Output standard autoflip signals only (Human, Pet, Car, etc) and apply
  // standard autoflip labels.
  optional bool output_standard_signals = 1 [default = true];
  // Output all signals (regardless of label) and set autoflip label as
  // 'Object'.  Can be combined with output_standard_signals giving each
  // detection a 'object' label and a autoflip sepcific label.
  optional bool output_all_signals = 2 [default = false];
}
