// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe.autoflip;

import "mediapipe/examples/desktop/autoflip/autoflip_messages.proto";
import "mediapipe/framework/calculator.proto";

// Next tag: 3
message SignalFusingCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional SignalFusingCalculatorOptions ext = 280092372;
  }
  // Setting related to each type of signal this calculator could process.
  repeated SignalSettings signal_settings = 1;

  // Force a flush of the frame buffer after this number of frames.
  optional int32 max_scene_size = 2 [default = 600];
}

// Next tag: 6
message SignalSettings {
  // The type of signal these settings pertain to.
  optional SignalType type = 1;

  // Force a normalized incoming score to be re-normalized to within this range.
  // (set values to min:0 and max:1 for no change in the incoming score)
  // Values must be between 0-1, min must be less than max.
  //
  // Example of score adjustment:
  // Incoming OCR score: .7
  // Min OCR Score: .9
  // Max OCR Score: 1.0
  // --Result: .97
  optional float min_score = 2 [default = 0];
  optional float max_score = 3 [default = 1.0];

  // Is this signal required within the output cropped video?  If it is it will
  // be included or the video will be marked as failed to convert.
  optional bool is_required = 4 [default = false];

  // When used with ContentZoomingCalculator, this flag can be set indicating
  // that areas outside of these salient regions can be cropped from the frame.
  // When no salient regions have this flag set true, no zooming is performed.
  // When one or more salient regions have this flag set true, the max zoom
  // value will be used that keeps all “only_required” detections within view.
  // The ContentZoomingCalculator currently supports zooming by finding the size
  // of non-salient top/bottom borders regions and provides this information to
  // the SceneCroppingCalculator for reframing.
  optional bool only_required = 5 [default = false];
}
