// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message MelSpectrumCalculatorOptions {
  extend CalculatorOptions {
    optional MelSpectrumCalculatorOptions ext = 78581812;
  }
  // The fields are to populate the config parameters in
  // audio/dsp/mfcc/mel_filterbank.h
  // but the names are chose to mirror
  // audio/hearing/filterbanks/cochlea_gammatone_filterbank.proto
  // and the default values match those in
  // speech/greco3/frontend/filter_bank.proto .

  // Total number of frequency bands to use.
  optional int32 channel_count = 1 [default = 20];
  // Lower edge of lowest triangular Mel band.
  optional float min_frequency_hertz = 2 [default = 125.0];
  // Upper edge of highest triangular Mel band.
  optional float max_frequency_hertz = 3 [default = 3800.0];
}

message MfccCalculatorOptions {
  extend CalculatorOptions {
    optional MfccCalculatorOptions ext = 78450441;
  }

  // Specification of the underlying mel filterbank.
  optional MelSpectrumCalculatorOptions mel_spectrum_params = 1;

  // How many MFCC coefficients to emit.
  optional uint32 mfcc_count = 2 [default = 13];
}
