// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message StabilizedLogCalculatorOptions {
  extend CalculatorOptions {
    optional StabilizedLogCalculatorOptions ext = 101978339;
  }

  // The calculator computes log(x + stabilizer). stabilizer must be >=
  // 0, with 0 indicating a lack of stabilization.
  optional float stabilizer = 1 [default = .00001];

  // If true, CHECK that all input values in are >= 0. If false, the
  // code will take the log of the potentially negative input values
  // plus the stabilizer.
  optional bool check_nonnegativity = 2 [default = true];

  // Support a fixed multiplicative scaling of the output.
  optional double output_scale = 3 [default = 1.0];
}
