// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message CollectionHasMinSizeCalculatorOptions {
  extend CalculatorOptions {
    optional CollectionHasMinSizeCalculatorOptions ext = 259397840;
  }

  // The minimum size an input iterable collection should have for the
  // calculator to output true.
  optional int32 min_size = 1 [default = 0];
}
