// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

// Options to NonMaxSuppression calculator, which performs non-maximum
// suppression on a set of detections.
message NonMaxSuppressionCalculatorOptions {
  extend CalculatorOptions {
    optional NonMaxSuppressionCalculatorOptions ext = 55383100;
  }

  // Number of input streams. Each input stream should contain a vector of
  // detections.
  optional int32 num_detection_streams = 1 [default = 1];

  // Maximum number of detections to be returned. If -1, then all detections are
  // returned.
  optional int32 max_num_detections = 2 [default = -1];

  // Minimum score of detections to be returned.
  optional float min_score_threshold = 6 [default = -1.0];

  // Jaccard similarity threshold for suppression -- a detection would suppress
  // all other detections whose scores are lower and overlap by at least the
  // specified threshold.
  optional float min_suppression_threshold = 3 [default = 1.0];

  // During the overlap computation, which is used to determine whether a
  // rectangle suppresses another rectangle, one can use the Jaccard similarity,
  // defined as the ration of the intersection over union of the two rectangles.
  // Alternatively a modified version of Jaccard can be used, where the
  // normalization is done by the area of the rectangle being checked for
  // suppression.
  enum OverlapType {
    UNSPECIFIED_OVERLAP_TYPE = 0;
    JACCARD = 1;
    MODIFIED_JACCARD = 2;
    INTERSECTION_OVER_UNION = 3;
  }
  optional OverlapType overlap_type = 4 [default = JACCARD];

  // Whether to put empty detection vector in output stream.
  optional bool return_empty_detections = 5;

  // Algorithms that can be used to apply non-maximum suppression.
  enum NmsAlgorithm {
    DEFAULT = 0;
    // Only supports relative bounding box for weighted NMS.
    WEIGHTED = 1;
  }
  optional NmsAlgorithm algorithm = 7 [default = DEFAULT];
}
