// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

// TODO: Switch to package mediapipe.
package mediapipe;

import "mediapipe/framework/calculator.proto";

// Options for PacketFrequencyCalculator.
message PacketFrequencyCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional PacketFrequencyCalculatorOptions ext = 168468918;
  }

  // Time window (in seconds) over which the packet frequency is computed. Must
  // be greater than 0 and less than 100 seconds (in order to limit memory
  // usage).
  optional double time_window_sec = 1 [default = 3.0];

  // Text identifiers for the input streams.
  repeated string label = 2;
}
