// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

// TODO: Switch to package mediapipe.
package mediapipe;

import "mediapipe/framework/calculator.proto";

message PacketLatencyCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional PacketLatencyCalculatorOptions ext = 172681421;
  }

  // Number of intervals for the latency histogram output.
  optional int64 num_intervals = 1 [default = 10];

  // Interval size (in microseconds) for the histogram.
  optional int64 interval_size_usec = 2 [default = 10000];

  // Reset time (in microseconds) for histogram and average. The histogram and
  // running average are initialized to zero periodically based on the specified
  // duration. Negative value implies never resetting the statistics.
  optional int64 reset_duration_usec = 3 [default = -1];

  // Identifier labels for each input packet stream. The order of labels must
  // correspond 1:1 with the input streams order. The labels are copied to the
  // latency information output by the calculator.
  repeated string packet_labels = 4;
}
