// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "mediapipe/util/color.proto";

message RectToRenderDataCalculatorOptions {
  extend CalculatorOptions {
    optional RectToRenderDataCalculatorOptions ext = 262270380;
  }

  // Whether the rendered rectangle should be filled.
  optional bool filled = 1;

  // Line color or filled color of the rectangle.
  optional Color color = 2;

  // Thickness of the line (applicable when the rectangle is not filled).
  optional double thickness = 3 [default = 1.0];

  // Whether the rendered rectangle should be an oval.
  optional bool oval = 4 [default = false];

  // Radius of top left corner circle. Only supported for oval=false,
  // filled=false.
  optional double top_left_thickness = 5;
}
