// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "mediapipe/util/color.proto";

message TimedBoxListToRenderDataCalculatorOptions {
  extend CalculatorOptions {
    optional TimedBoxListToRenderDataCalculatorOptions ext = 289899854;
  }

  // Color of boxes.
  optional Color box_color = 1;

  // Thickness of the drawing of boxes.
  optional double thickness = 2 [default = 1.0];
}
