// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message GlAnimationOverlayCalculatorOptions {
  extend CalculatorOptions {
    optional GlAnimationOverlayCalculatorOptions ext = 174760573;
  }

  // Default aspect ratio of rendering target width over height.
  // This specific value is for 3:4 view. Do not change this default value.
  optional float aspect_ratio = 1 [default = 0.75];
  // Default vertical field of view in degrees. This specific default value
  // is arbitrary. Do not change this default value. If you want to use
  // a different vertical_fov_degrees, set it in the options.
  optional float vertical_fov_degrees = 2 [default = 70.0];

  // Perspective projection matrix z-clipping near plane value.
  optional float z_clipping_plane_near = 3 [default = 0.1];
  // Perspective projection matrix z-clipping far plane value.
  optional float z_clipping_plane_far = 4 [default = 1000.0];

  // Speed at which to play the animation (in frames per second).
  optional float animation_speed_fps = 5 [default = 25.0];
}
