// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "mediapipe/gpu/scale_mode.proto";

// Next id: 10.
message GlScalerCalculatorOptions {
  extend CalculatorOptions {
    optional GlScalerCalculatorOptions ext = 166373014;
  }

  // Output dimensions.
  optional int32 output_width = 1;
  optional int32 output_height = 2;
  // A scale factor for output size, while keeping aspect ratio. It has lower
  // priority than the above two fields. That is, it is effective only when the
  // above two fields are unset.
  optional float output_scale = 7 [default = 1.0];
  // Counterclockwise rotation in degrees. Must be a multiple of 90.
  optional int32 rotation = 3;
  // Flip the output texture vertically. This is applied after rotation.
  optional bool flip_vertical = 4;
  // Flip the output texture horizontally. This is applied after rotation.
  optional bool flip_horizontal = 5;
  optional ScaleMode.Mode scale_mode = 6;
  // Whether to use nearest neighbor interpolation. Default to use linear
  // interpolation.
  optional bool use_nearest_neighbor_interpolation = 8 [default = false];
  // Whether the output format should match the input format. If true, it is
  // your responsibility to ensure the output format is valid to render to given
  // the current OpenGL configuration.
  optional bool use_input_format_for_output = 9 [default = false];
}
