// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from mediapipe/framework/packet_generator.proto.
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.
//
// Messages for specifying PacketGenerators.
// DEPRECATED: Use a Node to generate side packets.

syntax = "proto2";

package mediapipe;

option java_package = "com.google.mediapipe.proto";
option java_outer_classname = "PacketGeneratorProto";

// Options used by a PacketGenerator.
message PacketGeneratorOptions {
  option deprecated = true;

  // If true, this proto specifies a subset of field values,
  // which should override corresponding field values.
  optional bool merge_fields = 1 [default = true];

  extensions 20000 to max;
}

// The settings specifying a packet generator and how it is connected.
message PacketGeneratorConfig {
  option deprecated = true;

  // The name of the registered packet generator class.
  optional string packet_generator = 1;

  // The names of the input side packets.  The PacketGenerator can choose
  // to access its input side packets either by index or by tag.
  repeated string input_side_packet = 2;
  // DEPRECATED(mgeorg) The old name for input_side_packet.
  repeated string external_input = 1002;

  // The names of the output side packets that this generator produces.
  // The PacketGenerator can choose to access its output side packets
  // either by index or by tag.
  repeated string output_side_packet = 3;
  // DEPRECATED(mgeorg) The old name for output_side_packet.
  repeated string external_output = 1003;

  // The options for the packet generator.
  optional PacketGeneratorOptions options = 4;
}
