// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Proto for testing the Packet.

syntax = "proto2";

package mediapipe;

message PacketTestProto {
  // Tests that the tags used to encode the timestamp do not interfere with
  // proto tags.
  repeated int32 x = 1777;
  // The tag below = 1777 | (1 << 28).
  repeated int32 y = 268437233;
}

// A proto like InputCollection::Inputs which has embedded strings
// within it.
message SimpleProto {
  repeated bytes value = 1;
}

// A proto that acts as the proxy of SerializationProxyTestClass for
// serialization.
message SerializationProxyProto {
  optional bool bool_value = 1;
  repeated float float_value = 2;
  repeated string string_value = 3;
}

// This proto should be used only as an input to a calculator, to verify that
// that case is covered.
message InputOnlyProto {
  optional int32 x = 1;
}
