// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from mediapipe/framework/packet_factory.proto.
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.
//
// Messages for PacketFactory and PacketManager.

syntax = "proto2";

package mediapipe;

option java_package = "com.google.mediapipe.proto";
option java_outer_classname = "PacketFactoryProto";

// Options used by a PacketFactory to create the Packet.
message PacketFactoryOptions {
  extensions 20000 to max;
}

// A PacketFactory creates a side packet.
message PacketFactoryConfig {
  // The name of the registered packet factory class.
  optional string packet_factory = 1;

  // The name of the output side packet that this packet factory creates.
  optional string output_side_packet = 2;

  // DEPRECATED: The old name for output_side_packet.
  optional string external_output = 1002;

  // The options for the packet factory.
  optional PacketFactoryOptions options = 3;
}

// The configuration for a PacketManager.
message PacketManagerConfig {
  repeated PacketFactoryConfig packet = 1;
}
