// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from mediapipe/framework/status_handler.proto.
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.
//
// Messages for specifying StatusHandlers.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/mediapipe_options.proto";

option java_package = "com.google.mediapipe.proto";
option java_outer_classname = "StatusHandlerProto";

// The settings specifying a status handler and its required external inputs.
message StatusHandlerConfig {
  // The name of the registered status handler class.
  optional string status_handler = 1;  // required

  // The name of the input side packets.  The StatusHandler can access its
  // input side packets by index or by tag.  A StatusHandler will only
  // be called if all of its requested input side packets are available
  // (and won't be called if a PacketFactory or PacketGenerator which
  // produces one fails).
  repeated string input_side_packet = 2;
  // DEPRECATED(mgeorg) The old name for input_side_packet.
  repeated string external_input = 1002;

  // The options for the status handler.
  optional MediaPipeOptions options = 3;
}
