// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from mediapipe/framework/stream_handler.proto.
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/mediapipe_options.proto";

option java_package = "com.google.mediapipe.proto";
option java_outer_classname = "StreamHandlerProto";

// Settings specifying an input stream handler.
message InputStreamHandlerConfig {
  // Name of the registered input stream handler class.
  optional string input_stream_handler = 1
      [default = "DefaultInputStreamHandler"];

  // Options for the input stream handler.
  optional MediaPipeOptions options = 3;
}

// Settings specifying an output stream handler.
message OutputStreamHandlerConfig {
  // Name of the registered output stream handler class.
  optional string output_stream_handler = 1
      [default = "InOrderOutputStreamHandler"];

  // Names of the input side packets for the handler specifically and distinct
  // from the side packets for the calculator (but could be shared).
  repeated string input_side_packet = 2;

  // Options for the output stream handler.
  optional MediaPipeOptions options = 3;
}
