// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "mediapipe/util/tracking/flow_packager.proto";

message FlowPackagerCalculatorOptions {
  extend CalculatorOptions {
    optional FlowPackagerCalculatorOptions ext = 271236147;
  }

  optional mediapipe.FlowPackagerOptions flow_packager_options = 1;

  // Chunk size for caching files that are written to the externally specified
  // caching directory. Specified in msec.
  // Note that each chunk always contains at its end the first frame of the
  // next chunk (to enable forward tracking across chunk boundaries).
  optional int32 caching_chunk_size_msec = 2 [default = 2500];

  optional string cache_file_format = 3 [default = "chunk_%04d"];
}
