// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message OpenCvVideoEncoderCalculatorOptions {
  extend CalculatorOptions {
    optional OpenCvVideoEncoderCalculatorOptions ext = 207936763;
  }
  // The 4-character code of the codec to encode the video.
  optional string codec = 1;

  // The video format of the output video file.
  optional string video_format = 2;

  // The frame rate in Hz at which the video frames are output.
  optional double fps = 3;

  // Dimensions of the video in pixels.
  optional int32 width = 4;
  optional int32 height = 5;
}
