// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message VideoPreStreamCalculatorOptions {
  extend CalculatorOptions {
    optional VideoPreStreamCalculatorOptions ext = 151386123;
  }

  // An arbitrary number of frames per second.
  // Prefer the StandardFps enum to store industry-standard, safe FPS values.
  message Fps {
    // The possibly approximated value of the frame rate, in frames per second.
    // Unsafe to use in accurate computations because prone to rounding errors.
    // For example, the 23.976 FPS value has no exact representation as a
    // double.
    optional double value = 1;

    message Rational32 {
      optional int32 numerator = 1;
      optional int32 denominator = 2;
    }
    // The exact value of the frame rate, as a rational number.
    optional Rational32 ratio = 2;
  }
  optional Fps fps = 1;
}
