// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from
// mediapipe/framework/stream_handler/default_input_stream_handler.proto
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/mediapipe_options.proto";

// See DefaultInputStreamHandler for documentation.
message DefaultInputStreamHandlerOptions {
  extend MediaPipeOptions {
    optional DefaultInputStreamHandlerOptions ext = 164312821;
  }
  // batch_size determines how many input packets should be collected before
  // a calculator can process them. Once there are enough packets, Process
  // method of the Calculator is called sequentially. Currently, batching is not
  // supported for source nodes but it may be supported in the future.
  // Therefore, this field should not be specified for source nodes.
  optional int32 batch_size = 1 [default = 1];
}
