// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

message OpticalFlowFieldData {
  optional int32 width = 1;
  optional int32 height = 2;
  // Stores the two channels of the flow field in raster order.
  repeated float dx = 3 [packed = true];
  repeated float dy = 4 [packed = true];
}
