// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "tensorflow/core/framework/types.proto";

message ImageFrameToTensorCalculatorOptions {
  extend CalculatorOptions {
    optional ImageFrameToTensorCalculatorOptions ext = 120603667;
  }

  // If set, the output tensor will be of data type specified by this field.
  // Otherwise, the output tensor data type is equal to that of the input image
  // frame.
  optional tensorflow.DataType data_type = 1;

  // If set, the output tensor T is equal to (F - mean * J) / stddev, where F
  // and J are the input image frame and the all-ones matrix of the same size,
  // respectively.  Otherwise, T is equal to F.
  repeated float mean = 2;
  repeated float stddev = 3;
}
