// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// The option proto for the ObjectDetectionsTensorToDetectionsCalculator.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message ObjectDetectionsTensorToDetectionsCalculatorOptions {
  extend .mediapipe.CalculatorOptions {
    optional ObjectDetectionsTensorToDetectionsCalculatorOptions ext =
        192676232;
  }

  // The threshold used to compute the binary segmentation mask.
  optional float mask_threshold = 1 [default = 0.0];

  // The specific singleton dimensions to squeeze (remove). The calculator can
  // only removes dimensions of size 1.
  repeated int32 tensor_dim_to_squeeze = 2;
}
