// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "mediapipe/framework/formats/time_series_header.proto";

message TensorToMatrixCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional TensorToMatrixCalculatorOptions ext = 136654056;
  }

  // Any values present in this TimeSeriesHeader override the values in the
  // header from the reference stream if the reference stream is used.
  // The most common fields to override are the num_channels field which
  // typically correspond to the dimensionality of an output embedding and
  // the num_samples field which is generally 1 for an embedding.
  // If the sampling_rate is not specified in the time_series_header, then
  // the packet_rate from the reference stream will be used as the sampling_rate
  // which assumes that num_samples is 1.
  optional TimeSeriesHeader time_series_header_overrides = 1;
}
