// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message TensorToImageFrameCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional TensorToImageFrameCalculatorOptions ext = 142032475;
  }

  // Multiples floating point tensor outputs by this value before converting to
  // uint8. This is useful for converting from range [0, 1] to [0, 255]
  optional float scale_factor = 1 [default = 1.0];

  // If true, scales any FLOAT tensor input of [min, max] to be between [0, 255]
  // per frame. This overrides any explicit scale_factor.
  optional bool scale_per_frame_min_max = 2 [default = false];
}
