// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message TensorToVectorIntCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional TensorToVectorIntCalculatorOptions ext = 464933130;
  }

  // If true, unpack a 2d tensor (matrix) into a vector<vector<float>>. If
  // false, convert a 1d tensor (vector) into a vector<float>.
  optional bool tensor_is_2d = 1 [default = false];

  // If true, an N-D tensor will be flattened to a vector<float>. This is
  // exclusive with tensor_is_2d.
  optional bool flatten_nd = 2 [default = false];

  // If true, represents the vector as tokens and outputs just the position
  // of values above the threshold into the output vector.
  optional bool tensor_is_token = 3 [default = false];
  // Threshold for the token generation.
  optional float token_threshold = 4 [default = 0.5];

  // Values which overlap between timely following vectors. They are removed
  // from the output to reduce redundancy.
  optional int32 overlap = 5 [default = 0];
}
