// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message TensorToVectorFloatCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional TensorToVectorFloatCalculatorOptions ext = 120862965;
  }

  // If true, unpack a 2d tensor (matrix) into a vector<vector<float>>. If
  // false, convert a 1d tensor (vector) into a vector<float>.
  optional bool tensor_is_2d = 1 [default = false];

  // If true, an N-D tensor will be flattened to a vector<float>. This is
  // exclusive with tensor_is_2d.
  optional bool flatten_nd = 2 [default = false];
}
