// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

// Specifies options to TensorSqueezeDimensionsCalculator. Use this proto to
// configure which dimensions to squeeze (remove). It is only possible to remove
// dimensions of size 1.
// The fields 'squeeze_all_single_dims' and 'dim' are mutually exclusive.
message TensorSqueezeDimensionsCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional TensorSqueezeDimensionsCalculatorOptions ext = 115619805;
  }
  // Remove all dimensions with size 1.
  optional bool squeeze_all_single_dims = 1 [default = false];
  // Remove specific singleton dimensions.
  repeated int32 dim = 2;
}
