// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "tensorflow/core/framework/types.proto";

message VectorIntToTensorCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional VectorIntToTensorCalculatorOptions ext = 275364184;
  }
  enum InputSize {
    UNKNOWN = 0;
    INPUT_1D = 1;
    INPUT_2D = 2;
  }

  // If input_size is INPUT_2D, unpack a vector<vector<int>> to a
  // 2d tensor (matrix). If INPUT_1D, convert a single int or vector<int>
  // into a 1d tensor (vector).
  optional InputSize input_size = 1 [default = INPUT_1D];

  // If true, the output tensor is transposed.
  // Otherwise, the output tensor is not transposed.
  // It will be ignored if tensor_is_2d is INPUT_1D.
  optional bool transpose = 2 [default = false];

  optional tensorflow.DataType tensor_data_type = 3 [default = DT_INT32];

  // If true, the calculator will output the value as a scalar tensor.
  // This is only available for single values.
  optional bool scalar_output = 4;
}
