
type: "TrackingSubgraph"

input_stream: "input_frame"
input_stream: "match_image"
output_stream: "overlayed_frame"
output_stream: "tracked_boxes"

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_frame"
  input_stream: "FINISHED:overlayed_frame"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
    }
  }
  output_stream: "throttled_input_video_cpu"
}

node {
  calculator: "StreamToSidePacketCalculator"
  input_stream: "match_image"
  output_side_packet: "match_image_side_packet"
}

node {
  calculator: "SidePacketToStreamCalculator"
  input_stream: "TICK:throttled_input_video_cpu"
  input_side_packet: "match_image_side_packet"
  output_stream: "AT_TICK:match_image_packet"
}

node {
  calculator: "PacketClonerCalculator"
  input_stream: "TICK:throttled_input_video_cpu"
  input_stream: "throttled_input_video_cpu"
  input_stream: "match_image_packet"
  output_stream: "cloned_input_frame"
  output_stream: "cloned_match_image_packet"
}

node {
  calculator: "PreviousLoopbackCalculator"
  input_stream: "MAIN:cloned_input_frame"
  input_stream: "LOOP:homography"
  input_stream_info: {
    tag_index: "LOOP"
    back_edge: true
  }
  output_stream: "PREV_LOOP:prev_homography"
}

node: {
  calculator: "TrackingCalculator"
  input_stream: "PRIMARY_IMAGE:cloned_input_frame"
  input_stream : "SECONDARY_IMAGE:cloned_match_image_packet"
  input_stream: "FEEDBACK_I:prev_homography"
  output_stream: "OVERLAYED_IMAGE:overlayed_frame"
  output_stream: "FEEDBACK_O:homography"
  output_stream: "BOXES:tracked_boxes"
}