// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";
import "mediapipe/util/color.proto";

message RecolorCalculatorOptions {
  extend CalculatorOptions {
    optional RecolorCalculatorOptions ext = 252527117;
  }

  enum MaskChannel {
    UNKNOWN = 0;
    RED = 1;
    ALPHA = 2;
  }

  // Selects which channel of the MASK input to use for masking.
  optional MaskChannel mask_channel = 1 [default = RED];

  // Color to blend into input image where mask is > 0.
  // The blending is based on the input image luminosity.
  optional Color color = 2;

  // Swap the meaning of mask values for foreground/background.
  optional bool invert_mask = 3 [default = false];

  // Whether to use the luminance of the input image to further adjust the
  // blending weight, to help preserve image textures.
  optional bool adjust_with_luminance = 4 [default = true];
}
