// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// A protocol buffer encoding one or several classifications in an image. A
// classification is defined by label and corresponding score, representing the
// classifier confidence for the label.

syntax = "proto2";

package mediapipe;

option java_package = "com.google.mediapipe.formats.proto";
option java_outer_classname = "ClassificationProto";

message Classification {
  // The index of the class in the corresponding label map.
  optional int32 index = 1;
  // The probability score for this class.
  optional float score = 2;
  // Label or name of the class.
  optional string label = 3;
  // Optional human-readable string for display purposes.
  optional string display_name = 4;
}

// Group of Classification protos.
message ClassificationList {
  repeated Classification classification = 1;
}

// Group of ClassificationList protos.
message ClassificationListCollection {
  repeated ClassificationList classification_list = 1;
}
