// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

// A list of properties extracted from EXIF metadata from an image file.
message ImageFileProperties {
  // Image dimensions.
  optional uint32 image_width = 1;
  optional uint32 image_height = 2;
  // Focal length of camera lens in millimeters.
  optional double focal_length_mm = 3;
  // Focal length of camera lens in 35 mm equivalent.
  optional double focal_length_35mm = 4;
  // Focal length in pixels.
  optional double focal_length_pixels = 5;
}
