// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from
// mediapipe/framework/formats/matrix_data.proto
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.

syntax = "proto2";

package mediapipe;

option java_package = "com.google.mediapipe.formats.proto";
option java_outer_classname = "MatrixDataProto";

// Proto for serializing Matrix data.
// Data are stored in column-major order by default.
message MatrixData {
  optional int32 rows = 1;
  optional int32 cols = 2;

  repeated float packed_data = 3 [packed = true];

  enum Layout {
    COLUMN_MAJOR = 0;
    ROW_MAJOR = 1;
  }

  // Order in which the data are stored. Defaults to COLUMN_MAJOR, which matches
  // the default for mediapipe::Matrix and Eigen::Matrix*.
  optional Layout layout = 4 [default = COLUMN_MAJOR];
}
