input_stream: "input_video_gpu"
input_stream: "query_feats"
input_stream: "match_image"
input_stream: "enable_scanning"

output_stream: "output_video"
output_stream: "output_tensor_floats"
output_stream: "rr_index"
output_stream: "box_floats"

num_threads: 4
max_queue_size: 30

node {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "input_video_gpu"
  output_stream: "input_video_cpu"
}

node {
  calculator: "PassThroughCalculator"
  input_stream: "input_video_cpu"
  output_stream: "scanning_frame"
}


node {
  calculator: "StreamToSidePacketCalculator"
  input_stream: "enable_scanning"
  output_side_packet: "enable_scanning_side_packet"
}

node {
  calculator: "SidePacketToStreamCalculator"
  input_stream: "TICK:scanning_frame"
  input_side_packet: "enable_scanning_side_packet"
  output_stream: "AT_TICK:enable_scanning_packet"
}

node {
    calculator: "GateCalculator"
    input_stream: "scanning_frame"
    input_stream: "ALLOW:enable_scanning_packet"
    output_stream: "scanning_frame_enabled"
}

node {
  calculator: "ScanningSubgraph"
  input_stream: "scanning_frame_enabled"
  input_stream: "query_feats"
  output_stream: "FLOATS:output_tensor_floats"
  output_stream: "rr_index"
}

node {
  calculator: "PassThroughCalculator"
  input_stream: "input_video_cpu"
  output_stream: "tracking_frame"
}

node {
    calculator: "GateCalculator"
    input_stream: "tracking_frame"
    input_stream: "DISALLOW:enable_scanning_packet"
    output_stream: "tracking_frame_enabled"
}

node {
  calculator: "TrackingSubgraph"
  input_stream: "tracking_frame_enabled"
  input_stream: "match_image"
  output_stream: "box_output"
}

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video_cpu"
  input_stream: "FINISHED:viz"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
    }
  }
  output_stream: "throttled_input_video_cpu"
}

node: {
  calculator: "MotionAnalysisCalculator"
  input_stream: "VIDEO:throttled_input_video_cpu"
  output_stream: "CAMERA:camera_motion"
  output_stream: "FLOW:region_flow"

  node_options: {
    [type.googleapis.com/mediapipe.MotionAnalysisCalculatorOptions]: {
      analysis_options {
        analysis_policy: ANALYSIS_POLICY_CAMERA_MOBILE
        flow_options {
          fast_estimation_min_block_size: 50
          top_inlier_sets: 1
          frac_inlier_error_threshold: 3e-3
          downsample_mode: DOWNSAMPLE_TO_MIN_SIZE
          verification_distance: 2.3
          verify_long_feature_acceleration: true
          verify_long_feature_trigger_ratio: 0.4
          tracking_options {
            max_features: 500
            internal_tracking_direction: CONSECUTIVELY
            adaptive_extraction_levels: 10
            min_eig_val_settings {
              adaptive_lowest_quality_level: 3e-4
            }
            klt_tracker_implementation: KLT_OPENCV
          }
        }
      }
    }
  }
}

node: {
  calculator: "FlowPackagerCalculator"
  input_stream: "FLOW:region_flow"
  input_stream: "CAMERA:camera_motion"
  output_stream: "TRACKING:tracking_data"

  node_options: {
    [type.googleapis.com/mediapipe.FlowPackagerCalculatorOptions]: {
      flow_packager_options: {
        binary_tracking_data_support: false
      }
    }
  }
}


# Tracks box positions over time.
node: {
  calculator: "BoxTrackerCalculator"
  input_stream: "TRACKING:tracking_data"
  input_stream: "VIDEO:throttled_input_video_cpu"
  input_stream: "START_POS:box_output"
  output_stream: "VIZ:viz"
  output_stream: "BOXES:boxes"

  input_stream_handler {
    input_stream_handler: "SyncSetInputStreamHandler"
    options {
      [mediapipe.SyncSetInputStreamHandlerOptions.ext] {
        sync_set {
          tag_index: "TRACKING"
          tag_index: "VIDEO"
        }
        sync_set {
          tag_index: "START_POS"
        }
      }
    }
  }

  node_options: {
    [type.googleapis.com/mediapipe.BoxTrackerCalculatorOptions]: {
      tracker_options: {
        track_step_options {
          track_object_and_camera: true
          tracking_degrees: TRACKING_DEGREE_OBJECT_PERSPECTIVE
          inlier_spring_force: 0.0
          static_motion_temporal_ratio: 3e-2
          forced_pnp_tracking: true
        }
      }
      streaming_track_data_cache_size: 100
    }
  }
}

node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "SIZE:gated_image_size"
}

node {
  calculator: "BoxToFloatsCalculator"
  input_stream: "BOXES:boxes"
  input_stream: "PROPS:gated_image_size"
  output_stream: "BFLOATS:box_floats"
}

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "viz"
  output_stream: "output_video"
}