
input_stream: "input_video_gpu"
input_stream: "query_feats"
input_stream: "match_image"

output_stream: "output_video"
output_stream: "output_tensor_floats"
output_stream: "rr_index"
max_queue_size: 10
num_threads: 8

node {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "input_video_gpu"
  output_stream: "input_video_cpu"
}

node {
  calculator: "PictureLocalizationCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:localized_frame" 
}


node {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:localized_frame"
  output_stream: "IMAGE:resized_frame"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 640
      output_height: 480
      scale_mode: FIT
    }
  }
}

node {
  calculator: "FeatureDetection"
  input_stream: "IMAGE:resized_frame"
  output_stream: "FEATURES:feats"
}

node {
  calculator: "PacketClonerCalculator"
  input_stream: "TICK:query_feats"
  input_stream: "feats"
  input_stream: "query_feats"
  output_stream: "cloned_feats"
  output_stream: "cloned_query_feats"
}

node {
  calculator: "RerankCalculator"
  input_stream: "FEATURES:cloned_feats"
  input_stream: "QFEATURES:cloned_query_feats"
  output_stream: "RESULT:rr_index"
}

node {
  calculator: "FlowLimiterCalculator"
  input_stream: "localized_frame"
  input_stream: "FINISHED:output_tensor_floats"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
    }
  }
  output_stream: "throttled_input_video_full"
}

node {
  calculator: "GlobalFeaturesSubgraph"
  input_stream: "throttled_input_video_full"
  output_stream: "FLOATS:output_tensor_floats"
}


node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video_cpu"
  input_stream: "FINISHED:overlayed_frame"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 10
    }
  }
  output_stream: "throttled_input_video_cpu"
}

node {
  calculator: "TrackingSubgraph"
  input_stream: "throttled_input_video_cpu"
  input_stream: "match_image"
  output_stream: "overlayed_frame"
}

node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "overlayed_frame"
  output_stream: "output_video"
}
