// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe.autoflip;

// Options for the VisualScorer module.
// Next tag: 6
message VisualScorerOptions {
  // Weights for the various cues. A larger weight means that the corresponding
  // cue will be of higher importance when generating the combined score.
  optional float area_weight = 1 [default = 1.0];
  // Sharpness is not yet implemented.
  optional float sharpness_weight = 2 [default = 0.0];
  optional float colorfulness_weight = 3 [default = 0.0];
}
