// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message AudioStreamOptions {
  // The stream to decode.  Stream indexes start from 0 (audio and video
  // are handled separately).
  optional int64 stream_index = 1 [default = 0];

  // Process the file despite this stream not being present.
  optional bool allow_missing = 2 [default = false];

  // If true, failures to decode a frame of data will be ignored.
  optional bool ignore_decode_failures = 3 [default = false];

  // Output packets with regressing timestamps. By default those packets are
  // dropped.
  optional bool output_regressing_timestamps = 4 [default = false];

  // MPEG PTS timestamps roll over back to 0 after 26.5h. If this flag is set
  // we detect any rollover and continue incrementing timestamps past this
  // point. Set this flag if you want non-regressing timestamps for MPEG
  // content where the PTS may roll over.
  optional bool correct_pts_for_rollover = 5;
}

message AudioDecoderOptions {
  extend CalculatorOptions {
    optional AudioDecoderOptions ext = 263370674;
  }
  repeated AudioStreamOptions audio_stream = 1;

  // The start time in seconds to decode.
  optional double start_time = 2;
  // The end time in seconds to decode (inclusive).
  optional double end_time = 3;
}
