// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

option java_package = "com.google.mediapipe.util.proto";
option java_outer_classname = "ColorProto";

message Color {
  optional int32 r = 1;
  optional int32 g = 2;
  optional int32 b = 3;
}

// Mapping from string label to a color.
message ColorMap {
  map<string, Color> label_to_color = 1;
}
