// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.
//
// Forked from mediapipe/framework/tool/source.proto.
// The forked proto must remain identical to the original proto and should be
// ONLY used by mediapipe open source project.

syntax = "proto2";

package mediapipe;

// `MessageData`, like protobuf.Any, contains an arbitrary serialized protbuf
// along with a URL that describes the type of the serialized message.
message MessageData {
  // A URL/resource name that identifies the type of serialized protbuf.
  optional string type_url = 1;

  // Must be a valid serialized protocol buffer of the above specified type.
  optional bytes value = 2;
}

// Data for one Protobuf field or one MediaPipe packet.
message FieldData {
  oneof value {
    sint32 int32_value = 1;
    sint64 int64_value = 2;
    uint32 uint32_value = 3;
    uint64 uint64_value = 4;
    double double_value = 5;
    float float_value = 6;
    bool bool_value = 7;
    sint32 enum_value = 8;
    string string_value = 9;
    MessageData message_value = 10;
  }
}
