// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

// The option proto for the TensorsToLandmarksCalculator.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message TensorsToLandmarksCalculatorOptions {
  extend .mediapipe.CalculatorOptions {
    optional TensorsToLandmarksCalculatorOptions ext = 335742640;
  }

  enum Activation {
    NONE = 0;
    SIGMOID = 1;
  }

  // [Required] Number of landmarks from the output of the model.
  optional int32 num_landmarks = 1;

  // Size of the input image for the model. These options are used only when
  // normalized landmarks are needed. Z coordinate is scaled as X assuming
  // a weak perspective projection camera model.
  optional int32 input_image_width = 2;
  optional int32 input_image_height = 3;

  // Whether the detection coordinates from the input tensors should be flipped
  // vertically (along the y-direction). This is useful, for example, when the
  // input tensors represent detections defined with a coordinate system where
  // the origin is at the top-left corner, whereas the desired detection
  // representation has a bottom-left origin (e.g., in OpenGL).
  optional bool flip_vertically = 4 [default = false];

  // Whether the detection coordinates from the input tensors should be flipped
  // horizontally (along the x-direction). This is useful, for example, when the
  // input image is horizontally flipped in ImageTransformationCalculator
  // beforehand.
  optional bool flip_horizontally = 6 [default = false];

  // A value that Z coordinates should be divided by. This option is used only
  // when normalized landmarks are needed. It is applied in addition to Z
  // coordinate being re-scaled as X.
  optional float normalize_z = 5 [default = 1.0];

  // Apply activation function to the tensor representing landmark visibility.
  optional Activation visibility_activation = 7 [default = NONE];

  // Apply activation function to the tensor representing landmark presence.
  optional Activation presence_activation = 8 [default = NONE];
}
