// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message CallbackPacketCalculatorOptions {
  extend CalculatorOptions {
    optional CallbackPacketCalculatorOptions ext = 245965803;
  }

  enum PointerType {
    UNKNOWN = 0;
    VECTOR_PACKET = 1;
    POST_STREAM_PACKET = 2;
  }

  // The type of the data pointer that the callback will put data into.
  optional PointerType type = 1;
  // The location of the data stored as a string printed with
  // snprintf(address, sizeof(address), "%p", pointer).
  // This calculator only produces a reasonable callback if it is
  // constructed on the same machine as the original pointer was created on and
  // that pointer is still alive.
  optional bytes pointer = 2;
}
