// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

message PushPullOptions {
  // Sigma for color difference.
  optional float bilateral_sigma = 1 [default = 20.0];

  // Determines how fast confident values can propagate. Filters are normalized,
  // such that confidence dissipates quickly instead of propagating.
  // To ensure confidence propagates the importance weight is scaled by the
  // scalars specified below. Larger values yield quicker propagation.
  optional float pull_propagation_scale = 3 [default = 8.0];
  optional float push_propagation_scale = 4 [default = 8.0];

  // Above bilateral sigma is scaled at each level by the specified scale
  // (for push and pull phase). This is due to iterative downsampling of the
  // guidance image introduces errors making bilateral weighting increasingly
  // errorneous.
  optional float pull_bilateral_scale = 5 [default = 0.7];
  optional float push_bilateral_scale = 6 [default = 0.9];

  // Deprecated fields.
  extensions 2;
}
