// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

// The option proto for the TfLiteTensorsToClassificationCalculator.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message TfLiteTensorsToClassificationCalculatorOptions {
  extend .mediapipe.CalculatorOptions {
    optional TfLiteTensorsToClassificationCalculatorOptions ext = 266399463;
  }

  // Score threshold for preserving the class.
  optional float min_score_threshold = 1;
  // Number of highest scoring labels to output.  If top_k is not positive then
  // all labels are used.
  optional int32 top_k = 2;
  // Path to a label map file for getting the actual name of class ids.
  optional string label_map_path = 3;
  // Whether the input is a single float for binary classification.
  // When true, only a single float is expected in the input tensor and the
  // label map, if provided, is expected to have exactly two labels.
  // The single score(float) represent the probability of first label, and
  // 1 - score is the probabilility of the second label.
  optional bool binary_classification = 4;
}
