// Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
//
// PROPRIETARY AND CONFIDENTIAL
//
// This software and its documentation are the confidential and proprietary
// information of Flamingos Technologies Inc. ("Confidential Information").
// You shall not disclose such Confidential Information and shall use it
// only in accordance with the terms of the license agreement you entered
// into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
// or use of this software in source or binary forms is strictly prohibited.

syntax = "proto2";

package mediapipe;

import "mediapipe/framework/calculator.proto";

message TfLiteTensorsToSegmentationCalculatorOptions {
  extend mediapipe.CalculatorOptions {
    optional TfLiteTensorsToSegmentationCalculatorOptions ext = 252526026;
  }

  // Dimensions of input segmentation tensor to process.
  optional int32 tensor_width = 1;     // required
  optional int32 tensor_height = 2;    // required
  optional int32 tensor_channels = 3;  // required

  // How much to use previous mask when computing current one; range [0-1].
  // This is a tradeoff between responsiveness (0.0) and accuracy (1.0).
  optional float combine_with_previous_ratio = 4 [default = 1.0];

  // Model specific: Channel to use for processing tensor.
  optional int32 output_layer_index = 5 [default = 1];

  // Flip result image mask along y-axis.
  optional bool flip_vertically = 6;
}
