# Copyright 2024 Flamingos Technologies Inc. All Rights Reserved.
#
# PROPRIETARY AND CONFIDENTIAL
# 
# This software and its documentation are the confidential and proprietary
# information of Flamingos Technologies Inc. ("Confidential Information").
# You shall not disclose such Confidential Information and shall use it
# only in accordance with the terms of the license agreement you entered
# into with Flamingos Technologies Inc. Unauthorized copying, redistribution,
# or use of this software in source or binary forms is strictly prohibited.

load(
    "//mediapipe/framework/tool:mediapipe_files.bzl",
    "mediapipe_files",
)

licenses(["notice"])

package(default_visibility = ["//visibility:public"])

mediapipe_files(
    srcs = [
        "README.md",
        "hair_segmentation.tflite",
        "knift_float.tflite",
        "knift_float_1k.tflite",
        "knift_float_400.tflite",
        "knift_index.pb",
        "knift_labelmap.txt",
        "object_detection_saved_model/README.md",
        "object_detection_saved_model/model.ckpt.data-00000-of-00001",
        "object_detection_saved_model/model.ckpt.index",
        "object_detection_saved_model/model.ckpt.meta",
        "object_detection_saved_model/pipeline.config",
        "object_detection_saved_model/saved_model.pb",
        "ssdlite_object_detection.tflite",
        "ssdlite_object_detection_labelmap.txt",
    ],
)
